/**
 * FitLife Landing Page
 * Premium marketing page matching Stitch UI "Midnight Emerald" design.
 */
export function renderLanding() {
  return `
    <div class="min-h-screen bg-surface text-on-surface overflow-x-hidden">
      <!-- Hero Section -->
      <header class="relative min-h-screen flex flex-col">
        <!-- Background effects -->
        <div class="absolute inset-0 overflow-hidden">
          <div class="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[800px] rounded-full opacity-[0.07]"
               style="background: radial-gradient(circle, #22c55e 0%, transparent 70%);"></div>
          <div class="absolute bottom-0 right-0 w-[400px] h-[400px] rounded-full opacity-[0.04]"
               style="background: radial-gradient(circle, #9ddf2e 0%, transparent 70%);"></div>
        </div>

        <!-- Top Bar -->
        <nav class="relative z-10 flex items-center justify-between px-6 py-5 max-w-6xl mx-auto w-full">
          <div class="flex items-center gap-2">
            <div class="w-10 h-10 rounded-xl bg-gradient-to-br from-primary-container to-primary flex items-center justify-center">
              <span class="material-symbols-outlined text-on-primary text-xl" style="font-variation-settings: 'FILL' 1;">fitness_center</span>
            </div>
            <span class="text-xl font-bold">Fit<span class="text-primary">Life</span></span>
          </div>
          <button onclick="window.location.hash='/auth'" 
                  class="px-5 py-2.5 rounded-full text-sm font-semibold border border-outline-variant/30 text-on-surface hover:bg-surface-container-high/50 transition-all">
            Sign In
          </button>
        </nav>

        <!-- Hero Content -->
        <div class="relative z-10 flex-1 flex flex-col items-center justify-center px-6 pb-20 text-center max-w-3xl mx-auto">
          <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-8">
            <span class="material-symbols-outlined text-primary text-sm">auto_awesome</span>
            <span class="text-xs font-semibold text-primary uppercase tracking-wider">AI-Powered Performance</span>
          </div>
          
          <h1 class="text-4xl md:text-6xl font-bold leading-tight tracking-tight mb-6">
            Engineered for
            <span class="bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent"> Elite Performance</span>
          </h1>
          
          <p class="text-lg md:text-xl text-on-surface-variant max-w-xl mb-10 leading-relaxed">
            Your AI nutritionist, fitness coach, and wellness analyst. Precision-crafted meal plans, intelligent tracking, and real-time insights.
          </p>
          
          <div class="flex flex-col sm:flex-row gap-4 w-full max-w-md">
            <button onclick="window.location.hash='/auth?view=signup'" 
                    class="flex-1 px-8 py-4 rounded-full bg-primary-container text-on-primary-container font-bold text-base hover:shadow-lg hover:shadow-primary/20 transition-all duration-300 active:scale-[0.98]">
              Start Your Journey
            </button>
            <button onclick="window.location.hash='/auth?view=login'" 
                    class="flex-1 px-8 py-4 rounded-full border border-outline-variant/30 text-on-surface font-semibold text-base hover:bg-surface-container-high/50 transition-all duration-300">
              Welcome Back
            </button>
          </div>
        </div>

        <!-- Scroll indicator -->
        <div class="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 text-on-surface-variant animate-bounce">
          <span class="text-xs font-medium tracking-wider uppercase">Discover More</span>
          <span class="material-symbols-outlined text-lg">expand_more</span>
        </div>
      </header>

      <!-- Features Section -->
      <section class="py-20 px-6">
        <div class="max-w-6xl mx-auto">
          <div class="text-center mb-16">
            <h2 class="text-3xl md:text-4xl font-bold mb-4">Precision <span class="text-primary">Nutrition</span> Intelligence</h2>
            <p class="text-on-surface-variant text-lg max-w-2xl mx-auto">Every feature is designed for those who demand the best from their body and their technology.</p>
          </div>
          
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            ${[
              { icon: 'neurology', title: 'AI Meal Plans', desc: 'Personalized nutrition plans generated by advanced AI, calibrated to your unique physiology and goals.' },
              { icon: 'photo_camera', title: 'Vision Logging', desc: 'Snap a photo of your meal. AI instantly analyzes calories, macros, and nutritional content.' },
              { icon: 'trending_up', title: 'Body Analytics', desc: 'Track your transformation with intelligent progress monitoring and predictive insights.' },
              { icon: 'restaurant_menu', title: 'Smart Recipes', desc: 'AI-crafted recipes matching your dietary needs, preferences, and available ingredients.' },
              { icon: 'smart_toy', title: 'AI Coach', desc: '24/7 personal nutrition coach powered by AI. Ask anything about your diet and wellness.' },
              { icon: 'workspace_premium', title: 'Elite Dashboard', desc: 'Your command center for health metrics, streaks, achievements, and performance data.' },
            ].map(f => `
              <div class="group p-6 rounded-2xl border border-outline-variant/10 bg-surface-container-low/50 hover:bg-surface-container/70 hover:border-primary/20 transition-all duration-300">
                <div class="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                  <span class="material-symbols-outlined text-primary text-2xl">${f.icon}</span>
                </div>
                <h3 class="text-lg font-bold mb-2">${f.title}</h3>
                <p class="text-sm text-on-surface-variant leading-relaxed">${f.desc}</p>
              </div>
            `).join('')}
          </div>
        </div>
      </section>

      <!-- CTA Section -->
      <section class="py-20 px-6">
        <div class="max-w-2xl mx-auto text-center">
          <div class="p-10 rounded-3xl border border-outline-variant/10 bg-surface-container-low/30 relative overflow-hidden">
            <div class="absolute inset-0 opacity-[0.04]" style="background: radial-gradient(circle at top right, #22c55e, transparent 60%);"></div>
            <div class="relative z-10">
              <h2 class="text-3xl font-bold mb-4">Ready to Transform?</h2>
              <p class="text-on-surface-variant mb-8">Join thousands of elite performers who trust FitLife for their nutrition intelligence.</p>
              <button onclick="window.location.hash='/auth?view=signup'" 
                      class="px-10 py-4 rounded-full bg-primary-container text-on-primary-container font-bold text-base hover:shadow-lg hover:shadow-primary/20 transition-all duration-300 active:scale-[0.98]">
                Get Started Free
              </button>
            </div>
          </div>
        </div>
      </section>

      <!-- Footer -->
      <footer class="py-8 px-6 border-t border-outline-variant/10">
        <div class="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div class="flex items-center gap-2">
            <span class="text-sm font-bold">Fit<span class="text-primary">Life</span></span>
            <span class="text-xs text-on-surface-variant">&copy; 2025</span>
          </div>
          <div class="flex gap-6 text-xs text-on-surface-variant">
            <a href="#" class="hover:text-primary transition-colors">Privacy</a>
            <a href="#" class="hover:text-primary transition-colors">Terms</a>
            <a href="#" class="hover:text-primary transition-colors">Support</a>
          </div>
        </div>
      </footer>
    </div>`;
}
